### ISSUE TITLE
Missing documentation for @sigstore/CLI command

### ISSUE THREAD

**Issue by DhruvDange** [sigstore/sigstore-js#748] opened 2023-09-06 15:41 UTC
Missing documentation for @sigstore/CLI token command.
README has no mention of this command or its working.

**Comment by bdehamer** [comment] 2023-09-07 18:40
@DhruvDange thanks for your issue/PR.

The omission of the documentation for the `token` command was actually intentional. Note that the `token` command has been marked as [hidden](https://github.com/sigstore/sigstore-js/blob/3562d7a5a496f20a454b0abeea265a2547e6dea3/packages/cli/src/commands/token.ts#L7). This command was intended to be used only for internal testing and will likely be removed before the CLI hits a 1.0.0 release. For that reason, I'm not going to bother adding it to the readme

**Closed by bdehamer** 2023-09-07 18:40 UTC
Labels: enhancement
